# baseURL = 'https://b-mini.pages.dev/'
baseURL = 'https://b2t.be/'
languageCode = 'en-us'
title = 'B2T'

[Params]
copyright = '2024 &copy; Bart'
mainSections = ['pages','uniq','data']

[taxonomies]
tag = "tags"
docker = "dockers"

[permalinks]
# tags = "/tags/:slug/"
# dockers = "/data/dockers/:slug/"
[permalinks.term]
dockers = "/data/dockers/:slug/"
[permalinks.taxonomy]
dockers = "/data/dockers/:slug/"
